### ISSUE TITLE
Unsure about use

### ISSUE THREAD

**Issue by dotmilk** [maierfelix/mini-js#1]
Any attempt to use stub results in 

```
ReferenceError: __exports is not defined
    at Object.<anonymous> (/Users/sethprice/silverware/mini-js/bin/stub.js:1:17224)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Can I get a more detailed usage example?

**Comment by maierfelix** [comment]
https://github.com/maierfelix/mini-js/commit/238eca1e093e0f00f1b2b1398c21bdb81f18c7f0 should make outside usage much easier now

**Comment by dotmilk** [comment]
It does. Thanks.
